### PR TITLE
使用language域判断是否要替换“et al”为等

### PR DESCRIPTION
**Pull request by largeword**
在引用的论文中如不指定language或者language={en}则默认使用“et al”，如language={zh}则使用“等”

引用如下
`
@article{pedregosa2011scikit,
  title={Scikit-learn: Machine learning in Python},
  author={Pedregosa, Fabian and Varoquaux, Ga{\"e}l and Gramfort, Alexandre and Michel, Vincent and Thirion, Bertrand and Grisel, Olivier and Blondel, Mathieu and Prettenhofer, Peter and Weiss, Ron and Dubourg, Vincent and others},
  journal={Journal of machine learning research},
  volume={12},
  number={Oct},
  pages={2825--2830},
  year={2011}
}
`
`
@article{何清2014大数据下的机器学习算法综述,
  title={大数据下的机器学习算法综述},
  author={何清 and 李宁 and 罗文娟 and 史忠植},
  journal={模式识别与人工智能},
  volume={27},
  number={4},
  pages={327--336},
  year={2014},
  language={zh}
}
`

效果如下
`
[1]F. Pedregosa, G. Varoquaux, A. Gramfort, et al. Scikit-learn:  Machine learning in python[J].Journal of machine learning research, 2011, 12(Oct): 2825-2830
`
`
[2]何清,李宁,罗文娟,等.大数据下的机器学习算法综述[J].模式识别与人工智能, 2014,27(4): 327-336
`

### CODE REVIEW

**Comment by gzr-lgtm** [comment]
Hello, @largeword, thank you for your contribution! After testing your patch on my local environment, I found when the language attribute is set to `zh`, the patch worked perfectly. But if I do not set a language attribute for English cites, the whole BibTeX procedure will fail. Can you try to fix this? If not, that's totally ok, I'll just add a note for the users :-)

My .bib file:
```
% Ricci F, Rokach L, Shapira B. Recommender systems: introduction and challenges[M]//Recommender systems handbook. Springer, Boston, MA, 2015: 1-34.
@incollection{ricci2015recommender,
  title={Recommender systems: introduction and challenges},
  author={Ricci, Francesco and Rokach, Lior and Shapira, Bracha},
  booktitle={Recommender systems handbook},
  pages={1--34},
  year={2015},
  publisher={Springer}
}
...
```

Output:

```
This is BibTeX, Version 0.99d (TeX Live 2019)
The top-level auxiliary file: main.aux
The style file: njupthesis.bst
Database file #1: reference.bib
"zh" is a string literal, `language' is a missing field
---they aren't the same literal types for entry hsieh2017collaborative
while executing---line 606 of file njupthesis.bst
...
```

**Review by gzr-lgtm — CHANGES_REQUESTED** [review]
See https://github.com/imguozr/NJUPThesis-Bachelor/pull/5#issuecomment-615980721

**Comment by largeword** [comment]
> Hello, @largeword, thank you for your contribution! After testing your patch on my local environment, I found when the language attribute is set to `zh`, the patch worked perfectly. But if I do not set a language attribute for English cites, the whole BibTeX procedure will fail. Can you try to fix this? If not, that's totally ok, I'll just add a note for the users :-)
> 
> My .bib file:
> 
> ```
> % Ricci F, Rokach L, Shapira B. Recommender systems: introduction and challenges[M]//Recommender systems handbook. Springer, Boston, MA, 2015: 1-34.
> @incollection{ricci2015recommender,
>   title={Recommender systems: introduction and challenges},
>   author={Ricci, Francesco and Rokach, Lior and Shapira, Bracha},
>   booktitle={Recommender systems handbook},
>   pages={1--34},
>   year={2015},
>   publisher={Springer}
> }
> ...
> ```
> 
> Output:
> 
> ```
> This is BibTeX, Version 0.99d (TeX Live 2019)
> The top-level auxiliary file: main.aux
> The style file: njupthesis.bst
> Database file #1: reference.bib
> "zh" is a string literal, `language' is a missing field
> ---they aren't the same literal types for entry hsieh2017collaborative
> while executing---line 606 of file njupthesis.bst
> ...
> ```

之前的代码在overleaf上测试是不会出现编译错误的问题，但是为了增加兼容性和稳定性我稍微修改了一下代码，这次应该就没问题了

**Review by gzr-lgtm — APPROVED** [review]
This patch works fine! Thank you again 👍

**Comment by largeword** [comment]
> This patch works fine! Thank you again 👍

no problem

**Pull request merged**
